# Copyright (c) 2026 k.zhukov
# Licensed under the MIT License. See LICENSE in the project root for license information.
"""
C Code Generator (Decompiler Backend).
Translates simplified symbolic ASTs into clean, compilable, human-readable C functions.
"""
from typing import Dict, Any, List
import z3

class CCodeGenerator:
    def __init__(self, function_name: str = "validate_license", return_type: str = "uint32_t"):
        self.function_name = function_name
        self.return_type = return_type

    def ast_to_c_expression(self, expr: z3.ExprRef) -> str:
        """
        Recursively translates a Z3 BitVec AST node into a clean C expression.
        """
        if not z3.is_ast(expr):
            return str(expr)
            
        decl = expr.decl()
        kind = decl.kind()
        name = decl.name()
        num_args = expr.num_args()

        # Variable or Constant Terminal Nodes
        if num_args == 0:
            if z3.is_bv_value(expr):
                val = expr.as_long()
                return f"0x{val:X}U"
            return str(expr)

        args = [self.ast_to_c_expression(expr.arg(i)) for i in range(num_args)]

        # Bitwise and Arithmetic Operators
        if kind == z3.Z3_OP_BADD:
            return f"({args[0]} + {args[1]})"
        elif kind == z3.Z3_OP_BSUB:
            return f"({args[0]} - {args[1]})"
        elif kind == z3.Z3_OP_BMUL:
            return f"({args[0]} * {args[1]})"
        elif kind == z3.Z3_OP_BXOR:
            return f"({args[0]} ^ {args[1]})"
        elif kind == z3.Z3_OP_BAND:
            return f"({args[0]} & {args[1]})"
        elif kind == z3.Z3_OP_BOR:
            return f"({args[0]} | {args[1]})"
        elif kind == z3.Z3_OP_BNOT:
            return f"(~{args[0]})"
        elif kind == z3.Z3_OP_BSHL:
            return f"({args[0]} << {args[1]})"
        elif kind == z3.Z3_OP_BLSHR:
            return f"({args[0]} >> {args[1]})"
        elif kind == z3.Z3_OP_CONCAT:
            # Handle bit-concatenation / bit-slicing reconstructs
            return f"/* Concat */ ({' | '.join(args)})"
        elif kind == z3.Z3_OP_EXTRACT:
            high = expr.params()[0]
            low = expr.params()[1]
            mask = (1 << (high - low + 1)) - 1
            if low == 0:
                return f"({args[0]} & 0x{mask:X}U)"
            return f"(({args[0]} >> {low}) & 0x{mask:X}U)"
        else:
            return f"{name}({', '.join(args)})"

    def generate_c_function(self, expr: z3.ExprRef, input_params: List[str]) -> str:
        """
        Generates a complete standalone C function with header includes and type signatures.
        """
        c_expr = self.ast_to_c_expression(expr)
        params_str = ", ".join([f"uint32_t {p}" for p in input_params])
        
        lines = [
            "// Auto-generated by Argus De-obfuscation Engine",
            "// Author: k.zhukov (MIT License)",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            "",
            f"{self.return_type} {self.function_name}({params_str}) {{",
            f"    return {c_expr};",
            "}"
        ]
        return "\n".join(lines)
